name: Build and Upload packages for release (test monitoring)
true:
  pull_request: null
  push:
    branches:
    - '*'
jobs:
  debian-package-and-zips:
    runs-on: ubuntu-latest
    steps:
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    - name: Checkout repository
      uses: actions/checkout@v4
    - env:
        ENV_VAR: value
      name: Run bash script
      run: sudo bash -x ./Contrib/release.sh
    - name: Upload debian package
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        if-no-files-found: error
        name: packages-for-debian
        path: ./packages/*.deb
    - name: Upload zip & tar package
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        if-no-files-found: error
        name: packages-zip-tar
        path: './packages/*

          !./packages/*.deb

          '
    name: debian-package-and-zips
    if: ''
  installer-for-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Install WiX Toolset
      run: 'choco install wixtoolset --version=3.14.1 --force

        choco install 7zip.commandline

        '
    - name: Install Windows SDK
      run: 'choco install windows-sdk-10-version-1903-all

        '
    - env:
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      name: Build Windows Installer
      run: 'set -x

        ./Contrib/release.sh wininstaller

        '
      shell: bash
    - name: Upload windows installer
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        if-no-files-found: error
        name: packages-for-windows
        path: ./packages/*
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    name: installer-for-windows
    if: ''
  sign-all-packages:
    needs:
    - debian-package-and-zips
    - installer-for-windows
    runs-on: ubuntu-latest
    steps:
    - name: Download package for Debian
      uses: actions/download-artifact@v4
      with:
        name: packages-for-debian|
        path: ./packages
    - name: Download compressed packages
      uses: actions/download-artifact@v4
      with:
        name: packages-zip-tar
        path: ./packages
    - name: Download windows packages
      uses: actions/download-artifact@v4
      with:
        name: packages-for-windows
        path: ./packages
    - name: List downloaded files
      run: ls -l ./packages
    - name: PGP signing
      run: "set -x\necho \"${{ secrets.GPG_PRIVATE_KEY }}\" > private.key\ngpg --import\
        \ private.key\nrm private.key\necho \"${{ secrets.GPG_PASSPHRASE }}\" > passphrase.txt\n\
        export GPG_TTY=$(tty)\n\nfor FILE in \"./packages/*\"; do\n  sha256sum $FILE\
        \ >> SHA256SUMS\n  gpg --armor --detach-sign $FILE\ndone\n"
      shell: bash
    - uses: listendev/action@v0.11
      with:
        ci: only
        jwt: ${{ secrets.LSTN }}
    name: sign-all-packages
    if: ''
